name: OCaml on windows-2025 test

on:
  push:
    branches:
      - main

jobs:
  ocaml-test:
    runs-on: windows-2025
    steps:
      - uses: actions/cache@v4
        with:
          path: "C:\\opamroot.vhdx"
          key: opamroot-v1

      - uses: samypr100/setup-dev-drive@v3
        with:
          drive-size: 8GB
          drive-format: ReFS
          drive-type: Dynamic
          drive-path: opamroot.vhdx
          mount-if-exists: true
          native-dev-drive: true
          trusted-dev-drive: true
          env-mapping: |
            OPAMROOT,{{ DEV_DRIVE }}/.opam
            MSYS2_ROOT,{{ DEV_DRIVE }}/msys64

      - name: Copy MSYS2 to Dev Drive
        run: |
          $devDrive = $env:MSYS2_ROOT
          Write-Host "Copying MSYS2 to $devDrive..."
          $parentDir = Split-Path -Parent $devDrive
          if (-not (Test-Path $parentDir)) {
            New-Item -ItemType Directory -Force -Path $parentDir
          }
          Copy-Item -Path "C:\\msys64" -Destination $devDrive -Recurse -Force

      - name: Winget available?
        run: winget --help

      - name: Winget install OPAM
        run: |
          winget install --accept-source-agreements --accept-package-agreements -e --id OCaml.opam
          $userPath = [System.Environment]::GetEnvironmentVariable("Path", "User")
          $userPath.Split(';') | ForEach-Object {
            if ($_ -and (Test-Path $_)) {
              Add-Content -Path $env:GITHUB_PATH -Value $_
            }
          }

      # See https://github.com/ocaml/opam/issues/6472#issuecomment-2801536005
      - name: Allow long paths in the filesystem
        run: |
          # May not available in actions
          # $registryPath = "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem"
          # $propertyName = "LongPathsEnabled"
          # Set-ItemProperty -Path $registryPath -Name $propertyName -Type DWord -Value 1
          git config --system core.longpaths true

      - name: OPAM available?
        run: opam --version

      - name: OPAM init
        run: |
          opam init `
            --yes `
            --confirm-level=unsafe-yes `
            --bare `
            --bypass-checks `
            --enable-shell-hook `
            --disable-completion `
            --disable-sandboxing `
            --cygwin-local-install `
            --cygwin-location="$env:MSYS2_ROOT" `
            --no-opamrc `
            --assume-depexts
          # permanently disable handling of system packages
          opam option depext=false

      # - name: OPAM pin test
      #   run: opam pin add flow_parser https://github.com/rescript-lang/flow.git#d35a6f5c0cc219e85bbcb822d6f19ed9b2ec3448
      - name: OPAM create switch
        run: opam switch --no-install --packages=ocaml-base-compiler.5.3.0 create ${{ github.repository }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: OPAM install
        run: opam install . --yes --deps-only --with-test --with-dev-setup

      - name: dune build test
        run: opam exec -- dune build
